### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by wparry22** [saiemgilani/cfbfastR-py#5] opened 2021-10-12 00:44 UTC
Really appreciate the effort in putting this package together. Looks like there's no play by play data for 2021 though?

df4 = load_cfb_pbp(seasons=2021)
df4
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-176-68c3c5410150> in <module>
----> 1 df4 = load_cfb_pbp(seasons=2021)
      2 df4

~\Anaconda3\lib\site-packages\cfbfastR\cfb\__init__.py in load_cfb_pbp(seasons)

~\Anaconda3\lib\site-packages\pandas\io\parquet.py in read_parquet(path, engine, columns, **kwargs)
    310 
    311     impl = get_engine(engine)
--> 312     return impl.read(path, columns=columns, **kwargs)

~\Anaconda3\lib\site-packages\pandas\io\parquet.py in read(self, path, columns, **kwargs)
    121 
    122     def read(self, path, columns=None, **kwargs):
--> 123         path, _, _, should_close = get_filepath_or_buffer(path)
    124 
    125         kwargs["use_pandas_metadata"] = True

~\Anaconda3\lib\site-packages\pandas\io\common.py in get_filepath_or_buffer(filepath_or_buffer, encoding, compression, mode)
    170 
    171     if isinstance(filepath_or_buffer, str) and is_url(filepath_or_buffer):
--> 172         req = urlopen(filepath_or_buffer)
    173         content_encoding = req.headers.get("Content-Encoding", None)
    174         if content_encoding == "gzip":

~\Anaconda3\lib\site-packages\pandas\io\common.py in urlopen(*args, **kwargs)
    139     import urllib.request
    140 
--> 141     return urllib.request.urlopen(*args, **kwargs)
    142 
    143 

~\Anaconda3\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

~\Anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

~\Anaconda3\lib\urllib\request.py in http_response(self, request, response)
    638         # request was successfully received, understood, and accepted.
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)
    642 

~\Anaconda3\lib\urllib\request.py in error(self, proto, *args)
    567         if http_err:
    568             args = (dict, 'default', 'http_error_default') + orig_args
--> 569             return self._call_chain(*args)
    570 
    571 # XXX probably also want an abstract factory that knows when it makes

~\Anaconda3\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

~\Anaconda3\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

**Comment by wparry22** [comment] 2021-10-12 00:47
Also looks like there's not home or away points in cfb_load_schedule from week 2 on.

![image](https://user-images.githubusercontent.com/15950797/136871867-32451a29-f89e-423d-be05-7d75c5560072.png)

**Comment by saiemgilani** [comment] 2021-10-12 01:46
I'm revamping as we speak. I've failed you, and I do apologize

**Comment by wparry22** [comment] 2021-10-13 02:16
Appreciate it, Saiem. You’re a legend

**Comment by saiemgilani** [comment] 2021-10-14 21:14
the schedules should work now

**Comment by saiemgilani** [comment] 2021-12-23 00:09
Closing because cfbfastR-py will be archived soon and while the issue is still valid, will need to be opened on sportsdataverse-py's repo [https://github.com/saiemgilani/sportsdataverse-py/issues](https://github.com/saiemgilani/sportsdataverse-py/issues)

**Closed by saiemgilani** 2021-12-23 00:09 UTC
